
//! Autogenerated weights for `thea_council`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-05-07, STEPS: `100`, REPEAT: 200, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Ubuntu-2204-jammy-amd64-base`, CPU: `Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./parachain-polkadex-node
// benchmark
// pallet
// --pallet
// thea_council
// --steps
// 100
// --repeat
// 200
// --extrinsic
// *
// --output
// thea_council_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `thea_council`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::TheaCouncilWeightInfo for WeightInfo<T> {
    // Storage: TheaCouncil ActiveCouncilMembers (r:1 w:0)
    // Storage: TheaCouncil PendingCouncilMembers (r:1 w:1)
    // Storage: TheaCouncil Proposals (r:1 w:1)
    /// The range of component `b` is `[1, 1000]`.
    /// The range of component `b` is `[1, 1000]`.
    fn add_member(b: u32, ) -> Weight {
        // Minimum execution time: 19_985 nanoseconds.
        Weight::from_ref_time(20_893_948)
            // Standard Error: 2
            .saturating_add(Weight::from_ref_time(47).saturating_mul(b.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    // Storage: TheaCouncil ActiveCouncilMembers (r:1 w:1)
    // Storage: TheaCouncil Proposals (r:1 w:1)
    /// The range of component `b` is `[1, 1000]`.
    /// The range of component `b` is `[1, 1000]`.
    fn remove_member(_b: u32, ) -> Weight {
        // Minimum execution time: 21_159 nanoseconds.
        Weight::from_ref_time(22_185_949)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    // Storage: TheaCouncil PendingCouncilMembers (r:1 w:1)
    // Storage: TheaCouncil ActiveCouncilMembers (r:1 w:1)
    /// The range of component `b` is `[1, 1000]`.
    /// The range of component `b` is `[1, 1000]`.
    fn claim_membership(b: u32, ) -> Weight {
        // Minimum execution time: 16_780 nanoseconds.
        Weight::from_ref_time(17_554_288)
            // Standard Error: 1
            .saturating_add(Weight::from_ref_time(35).saturating_mul(b.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    // Storage: TheaCouncil ActiveCouncilMembers (r:1 w:0)
    // Storage: XcmHelper PendingWithdrawals (r:1 w:1)
    /// The range of component `b` is `[1, 1000]`.
    /// The range of component `b` is `[1, 1000]`.
    fn delete_transaction(_b: u32, ) -> Weight {
        // Minimum execution time: 19_547 nanoseconds.
        Weight::from_ref_time(20_515_337)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}
