// This file is part of Polkadex.

// Copyright (C) 2020-2023 Polkadex oü.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0

// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.

//! Autogenerated weights for `thea_council`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-05-21, STEPS: `100`, REPEAT: 200, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Ubuntu-2204-jammy-amd64-base`, CPU: `Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./parachain-polkadex-node
// benchmark
// pallet
// --pallet
// thea_council
// --steps
// 100
// --repeat
// 200
// --extrinsic
// *
// --output
// thea_council_weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `thea_council`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> crate::TheaCouncilWeightInfo for WeightInfo<T> {
    // Storage: TheaCouncil ActiveCouncilMembers (r:1 w:0)
    // Storage: TheaCouncil PendingCouncilMembers (r:1 w:1)
    // Storage: TheaCouncil Proposals (r:1 w:1)
    /// The range of component `b` is `[1, 1000]`.
    /// The range of component `b` is `[1, 1000]`.
    fn add_member(_b: u32, ) -> Weight {
        // Minimum execution time: 20_302 nanoseconds.
        Weight::from_ref_time(21_269_737)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    // Storage: TheaCouncil ActiveCouncilMembers (r:1 w:1)
    // Storage: TheaCouncil Proposals (r:1 w:1)
    /// The range of component `b` is `[1, 1000]`.
    /// The range of component `b` is `[1, 1000]`.
    fn remove_member(b: u32, ) -> Weight {
        // Minimum execution time: 21_273 nanoseconds.
        Weight::from_ref_time(22_154_977)
            // Standard Error: 2
            .saturating_add(Weight::from_ref_time(178).saturating_mul(b.into()))
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    // Storage: TheaCouncil PendingCouncilMembers (r:1 w:1)
    // Storage: TheaCouncil ActiveCouncilMembers (r:1 w:1)
    /// The range of component `b` is `[1, 1000]`.
    /// The range of component `b` is `[1, 1000]`.
    fn claim_membership(_b: u32, ) -> Weight {
        // Minimum execution time: 17_286 nanoseconds.
        Weight::from_ref_time(18_129_751)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
    }
    // Storage: TheaCouncil ActiveCouncilMembers (r:1 w:0)
    // Storage: XcmHelper PendingWithdrawals (r:1 w:1)
    /// The range of component `b` is `[1, 1000]`.
    /// The range of component `b` is `[1, 1000]`.
    fn delete_transaction(_b: u32, ) -> Weight {
        // Minimum execution time: 19_627 nanoseconds.
        Weight::from_ref_time(20_419_069)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
    }
}
