./target/release/parachain-collator \
--alice \
--collator \
--force-authoring \
--chain polkadot-parachain-raw.json \
--base-path parachain/alice \
--port 40333 \
--ws-port 8844 \
-- \
--execution wasm \
--chain polkadot.json \
--port 30343 \
--ws-port 9977
